path,msg_id,msg,alerts,chosen,In which repository the modification was done?,In which pull request the modification was done?,Do you consider the removed alert harmful?,Why do you consider it harmful (or harmless)?,"What is the code quality (1 lowest, 10 best)? Code quality refers to the code prior to the pull request.",Why do you consider the code quality as such?,"What is the expected benefit(1 – negative, 5 – neutral, 10 – great)?",Why do you consider the pull request to improve the code (or not improve it)?
src\models\base.py,W0107,unnecessary-pass,1,1,gabfl/vault,Won’t fix,No,The pass is in declaration of an empty base class (which is strange). Removing the pass will work but will look like forgeting content., , , , 
src\views\setup.py,C0301,line-too-long,1,1,gabfl/vault,https://github.com/gabfl/vault/pull/82,No,Line was one letter too long,6,some multiple returns,5,alert not important
src\tools\troubleshoot_db.py,R1719,simplifiable-if-expression,1,1,gabfl/vault,https://github.com/gabfl/vault/pull/82,Yes," if result_proxy.fetchall() == [(123,)] can result in only True or False, the external condition is not needed.
However, if result_proxy.fetchall() might return Noe, the external condition can translate it to False.

The external condition hurt readability since it takes a bit to verify what it does.
bool is a simpler implementation

See
https://stackoverflow.com/questions/76094401/the-if-expression-can-be-replaced-with-test-simplifiable-if-expression",7,OK code,6,improved readability
src\views\menu.py,W0718,broad-exception-caught,1,1,gabfl/vault,https://github.com/gabfl/vault/pull/82,Yes," Code deliberately catches Exception, after catching KeyboardInterrupt.
However, looking at the protected code it seems that no other exception can be raised.
Hence, instead of narrowing the exception, I removed it.",7,OK code,6,improved readability
src\lib\Config.py,C0301,line-too-long,1,1,gabfl/vault,https://github.com/gabfl/vault/pull/82,No,"Made the long, yet readable, comment shorter",7,OK code,5,alert not important
src\modules\autocomplete.py,W0718,broad-exception-caught,1,1,gabfl/vault,https://github.com/gabfl/vault/pull/82,Yes," Code deliberately catches Exception, after catching KeyboardInterrupt.
However, looking at the protected code it seems that no other exception can be raised.
Hence, instead of narrowing the exception, I removed it.",7,OK code,6,improved readability
src\views\secrets.py,R0912,too-many-branches,1,1,gabfl/vault,Won’t fix,Yes,Code gets an attribute name and goes on them in a switch-like structure. Handling almost identical yet assigned to the object attribute and exit by value. It's tempting to create a single function yet its implementation will require playing with the class properties. The exit will require more changes. Code is not nice but I don’t have a nicer solution.,4, , , 
src\modules\misc.py,W0718,broad-exception-caught,1,1,gabfl/vault,https://github.com/gabfl/vault/pull/82,Yes," Exception is too wide. os.path.exists does not throw exceptions. os.makedirs might throw OSError (e.g., in a bad path).  See https://stackoverflow.com/questions/2383816/how-can-i-make-an-error-verifiy-with-os-makedirs-in-python As extra safety, though the code checks just before for the directory, catch it too in case a different process will be able to create it before.",6,minor not optimal implementations,6,improved readability
src\views\import_export.py,C0301,line-too-long,1,1,gabfl/vault,https://github.com/gabfl/vault/pull/82,No,Made a readable comment line shorter,7,uses strings as return values,5,alert not important
src\views\migration.py,C0301,line-too-long,1,1,gabfl/vault,https://github.com/gabfl/vault/pull/82,No," Made the line shorter. Since the string is also formatted, parenthesis are added for operations precedence.",5,Multiple exit points,4,code is a bit more complex now
src\modules\carry.py,C0301,line-too-long,1,1,,Won’t fix,Yes,"In the documentation, the long line is due to a very long url. Splitting it will be worse.", , , , 
src\views\categories.py,C0325,superfluous-parens,1,1,gabfl/vault,https://github.com/gabfl/vault/pull/82,Yes,Replaced (True) to True,6,using letters instead of constants,6,improved readability
src\models\base.py,C0301,line-too-long,1,0,, , , , , , , 
src\tools\troubleshoot_db.py,C0301,line-too-long,1,0,, , , , , , , 
src\views\menu.py,C0301,line-too-long,1,0,, , , , , , , 
src\views\menu.py,C0325,superfluous-parens,1,0,, , , , , , , 
src\vault.py,C0301,line-too-long,4,0,, , , , , , , 
src\views\__init__.py,R0801,duplicate-code,4,0,, , , , , , , 
src\views\secrets.py,C0301,line-too-long,3,0,, , , , , , , 
src\views\secrets.py,R0911,too-many-return-statements,3,0,, , , , , , , 
src\views\secrets.py,R0915,too-many-statements,1,0,, , , , , , , 
src\views\secrets.py,W0718,broad-exception-caught,1,0,, , , , , , , 
src\modules\misc.py,C0301,line-too-long,6,0,, , , , , , , 
src\views\import_export.py,W0718,broad-exception-caught,2,0,, , , , , , , 
src\views\migration.py,W0718,broad-exception-caught,1,0,, , , , , , , 
src\views\categories.py,C0301,line-too-long,3,0,, , , , , , , 
